//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string itemID { get; set; }
        public string categoryID { get; set; }
        public string name { get; set; }
        public Nullable<int> limitQuantity { get; set; }
        public string suppliedBy { get; set; }
        public byte[] image { get; set; }
        public Nullable<float> purchase_price { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ReadyMadeProduct ReadyMadeProduct { get; set; }
    }
}
