//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarasi_HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadyMadeProduct
    {
        public string productID { get; set; }
        public Nullable<float> sellingPrice { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
